CREATE INDEX ON :EMR(id);

//DELETE ALL ELETRONIC MEDICAL RECORDER -> EMR
MATCH (emr:EMR) DETACH DELETE emr;

//CREATE EMR CARDS
CREATE
(:EMR {id: '!12345FFF'}),
(:EMR {id: '@23456AAA'}),
(:EMR {id: '#34567XXX'}),
(:EMR {id: '$43210TTT'});
