//CLEAR ALL INDEXES
DROP INDEX complicationInPortugueseIDX IF EXISTS;
DROP INDEX allergyInPortugueseIDX IF EXISTS;
DROP INDEX diseaseInPortugueseIDX IF EXISTS;
DROP INDEX intoleranceInPortugueseIDX IF EXISTS;
DROP INDEX specialtyInPortugueseIDX IF EXISTS;
DROP INDEX personUuidIDX IF EXISTS;
DROP INDEX patientUuidIDX IF EXISTS;
DROP INDEX emrUuidIDX IF EXISTS;
DROP INDEX vaccineCardUuidIDX IF EXISTS;
DROP INDEX diagUuidIDX IF EXISTS;
DROP INDEX dayUuidIDX IF EXISTS;
DROP INDEX monthUuidIDX IF EXISTS;

//CLEAR ALL CONSTRAINTS
DROP CONSTRAINT complicationName IF EXISTS;
DROP CONSTRAINT allergyName IF EXISTS;
DROP CONSTRAINT diseaseName IF EXISTS;
DROP CONSTRAINT intoleranceName IF EXISTS;
DROP CONSTRAINT specialtyInPortuguese IF EXISTS;
DROP CONSTRAINT personUuid IF EXISTS;
DROP CONSTRAINT patientUuidIDX IF EXISTS;

//CLEAR ALL DATA
MATCH(all) DETACH DELETE all ;
