//CREATE INDEX & CONSTRAINT
CREATE INDEX allergyInPortugueseIDX IF NOT EXISTS FOR (allergy:Allergy) ON (allergy.inPortuguese);
CREATE CONSTRAINT allergyName IF NOT EXISTS ON (allergy:Allergy) ASSERT allergy.name IS UNIQUE;

//CREATE FEW ALLERGIES TO ALLOW PoC
CREATE
(:Allergy {uuid: apoc.create.uuid(), name: 'Cream', inPortuguese: 'Creme', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Soap', inPortuguese: 'Sabonete', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Make up', inPortuguese: 'Maquiagem', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'perfume', inPortuguese: 'Perfume', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Latex Product', inPortuguese: 'Produto de Látex', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Bijou', inPortuguese: 'Bijuteria', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Ink', inPortuguese: 'Tinta', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Mosquito', inPortuguese: 'Mosquito', type: 'Insect'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Bee', inPortuguese: 'Abelha', type: 'Insect'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Flea', inPortuguese: 'Pulga', type: 'Insect'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Cat', inPortuguese: 'Gato', type: 'Animal'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Puppy', inPortuguese: 'Cachorro', type: 'Animal'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Ant', inPortuguese: 'Formiga', type: 'Insect'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Wasp', inPortuguese: 'Vespa', type: 'Insect'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Tick', inPortuguese: 'Carrapato', type: 'Insect'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Leggy', inPortuguese: 'Pernilongo', type: 'Insect'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Rubber', inPortuguese: 'Borrachudo', type: 'Insect'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Aspirin', inPortuguese: 'Aspirina', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Dipyrone', inPortuguese: 'Dipirona', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Paracetamol', inPortuguese: 'Paracetamol', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Diclofenac', inPortuguese: 'Diclofenaco', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Penicillin', inPortuguese: 'Penicilina', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Sulfa', inPortuguese: 'Sulfa', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Quinolone', inPortuguese: 'Quinolona', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Erythromycin', inPortuguese: 'Eritromicina', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Azithromycin', inPortuguese: 'Azitromicina', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Iodinated Contrast', inPortuguese: 'Contraste Iodado', type: 'Drug'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Mite', inPortuguese: 'Ácaro', type: 'Insect'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Dust', inPortuguese: 'Poeira', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Mold', inPortuguese: 'Mofo', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Pollen', inPortuguese: 'Pólen', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Smoke', inPortuguese: 'Fumaça', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Pollution', inPortuguese: 'Poluição', type: 'Other'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Milk', inPortuguese: 'Leite', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Egg', inPortuguese: 'Ovo', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Wheat', inPortuguese: 'Trigo', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Peanut', inPortuguese: 'Amendoim', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Seafood', inPortuguese: 'Frutos do Mar', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Dry Fruits', inPortuguese: 'Frutas Secas', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Soy', inPortuguese: 'Soja', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Fish', inPortuguese: 'Peixe', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Crustacean', inPortuguese: 'Crustáceo', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Mollusk', inPortuguese: 'Molusco', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Gluten', inPortuguese: 'Glúten', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Shrimp', inPortuguese: 'Camarão', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Squid', inPortuguese: 'Lula', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Pufferfish', inPortuguese: 'Baiacu', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Chocolate', inPortuguese: 'Chocolate', type: 'Food'}),
(:Allergy {uuid: apoc.create.uuid(), name: 'Caviar', inPortuguese: 'Caviar', type: 'Food'})
;
