version: "3"

services:
  app:
    build: .
    container_name: emr_app
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - db

  db:
    build: .docker/neo4j
    #image: neo4j:4.3.1-enterprise
    container_name: emr_neo4j
    restart: unless-stopped
    tty: true
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/docker-neo4j/neo4j/conf:/var/lib/neo4j/conf
      - $HOME/docker-neo4j/neo4j/data:/var/lib/neo4j/data
      - $HOME/docker-neo4j/neo4j/import:/var/lib/neo4j/import
      - $HOME/docker-neo4j/neo4j/logs:/var/lib/neo4j/logs
      - $HOME/docker-neo4j/neo4j/plugins:/var/lib/neo4j/plugins
    environment: 
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
