//CREATE ALL DOSES FOR ALL VACCINES UNDER AGE OF 14 TO ALLOW PoC
CREATE
(:VaccineDose {name: 'Unique', vaccineName: 'BCG ID', fromAgeInMonths: toInteger(1), toAgeInMonths:toInteger(1), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'Hepatite B', fromAgeInMonths: toInteger(1), toAgeInMonths:toInteger(1), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'Hepatite B', fromAgeInMonths: toInteger(2), toAgeInMonths:toInteger(2), classification: 'Mandatory'}),
(:VaccineDose {name: '3rd dose', vaccineName: 'Hepatite B', fromAgeInMonths: toInteger(6), toAgeInMonths:toInteger(6), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'DTPw', fromAgeInMonths: toInteger(2), toAgeInMonths:toInteger(2), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'DTPw', fromAgeInMonths: toInteger(4), toAgeInMonths:toInteger(4), classification: 'Mandatory'}),
(:VaccineDose {name: '3rd dose', vaccineName: 'DTPw', fromAgeInMonths: toInteger(6), toAgeInMonths:toInteger(6), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'DTPw', fromAgeInMonths: toInteger(15), toAgeInMonths:toInteger(18), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'DTPw', fromAgeInMonths: toInteger(48), toAgeInMonths:toInteger(60), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'H Influenzae', fromAgeInMonths: toInteger(2), toAgeInMonths:toInteger(2), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'H Influenzae', fromAgeInMonths: toInteger(4), toAgeInMonths:toInteger(4), classification: 'Mandatory'}),
(:VaccineDose {name: '3rd dose', vaccineName: 'H Influenzae', fromAgeInMonths: toInteger(6), toAgeInMonths:toInteger(6), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'H Influenzae', fromAgeInMonths: toInteger(15), toAgeInMonths:toInteger(18), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'Pólio VIP', fromAgeInMonths: toInteger(2), toAgeInMonths:toInteger(2), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'Pólio VIP', fromAgeInMonths: toInteger(4), toAgeInMonths:toInteger(4), classification: 'Mandatory'}),
(:VaccineDose {name: '3rd dose', vaccineName: 'Pólio VIP', fromAgeInMonths: toInteger(6), toAgeInMonths:toInteger(6), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'Pólio VOP', fromAgeInMonths: toInteger(15), toAgeInMonths:toInteger(18), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'Pólio VOP', fromAgeInMonths: toInteger(48), toAgeInMonths:toInteger(60), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'Rotavírus', fromAgeInMonths: toInteger(2), toAgeInMonths:toInteger(4), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'Rotavírus', fromAgeInMonths: toInteger(5), toAgeInMonths:toInteger(8), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'VPC10', fromAgeInMonths: toInteger(2), toAgeInMonths:toInteger(3), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'VPC10', fromAgeInMonths: toInteger(4), toAgeInMonths:toInteger(6), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'VPC10', fromAgeInMonths: toInteger(12), toAgeInMonths:toInteger(15), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'ACWY/C', fromAgeInMonths: toInteger(3), toAgeInMonths:toInteger(5), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'ACWY/C', fromAgeInMonths: toInteger(6), toAgeInMonths:toInteger(8), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'ACWY/C', fromAgeInMonths: toInteger(12), toAgeInMonths:toInteger(15), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'ACWY/C', fromAgeInMonths: toInteger(60), toAgeInMonths:toInteger(72), classification: 'Optional'}),
(:VaccineDose {name: '1st dose', vaccineName: 'Meningocócica B', fromAgeInMonths: toInteger(3), toAgeInMonths:toInteger(3), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'Meningocócica B', fromAgeInMonths: toInteger(5), toAgeInMonths:toInteger(5), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'Meningocócica B', fromAgeInMonths: toInteger(12), toAgeInMonths:toInteger(15), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(6), toAgeInMonths:toInteger(12), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(13), toAgeInMonths:toInteger(24), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(25), toAgeInMonths:toInteger(36), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(37), toAgeInMonths:toInteger(48), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(49), toAgeInMonths:toInteger(60), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(61), toAgeInMonths:toInteger(72), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(73), toAgeInMonths:toInteger(84), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(85), toAgeInMonths:toInteger(96), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(97), toAgeInMonths:toInteger(108), classification: 'Mandatory'}),
(:VaccineDose {name: 'Annual', vaccineName: '3V', fromAgeInMonths: toInteger(109), toAgeInMonths:toInteger(120), classification: 'Mandatory'}),
(:VaccineDose {name: 'Unique', vaccineName: 'Febre amarela', fromAgeInMonths: toInteger(9), toAgeInMonths:toInteger(9), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'Hepatite A', fromAgeInMonths: toInteger(12), toAgeInMonths:toInteger(12), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'Hepatite A', fromAgeInMonths: toInteger(18), toAgeInMonths:toInteger(18), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'BCG', fromAgeInMonths: toInteger(12), toAgeInMonths:toInteger(12), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'BCG', fromAgeInMonths: toInteger(15), toAgeInMonths:toInteger(24), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'Varicela', fromAgeInMonths: toInteger(12), toAgeInMonths:toInteger(12), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'Varicela', fromAgeInMonths: toInteger(15), toAgeInMonths:toInteger(24), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'HPV4', fromAgeInMonths: toInteger(108), toAgeInMonths:toInteger(119), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'HPV4', fromAgeInMonths: toInteger(120), toAgeInMonths:toInteger(132), classification: 'Mandatory'}),
(:VaccineDose {name: '1st dose', vaccineName: 'DTPa', fromAgeInMonths: toInteger(2), toAgeInMonths:toInteger(2), classification: 'Mandatory'}),
(:VaccineDose {name: '2nd dose', vaccineName: 'DTPa', fromAgeInMonths: toInteger(4), toAgeInMonths:toInteger(4), classification: 'Mandatory'}),
(:VaccineDose {name: '3rd dose', vaccineName: 'DTPa', fromAgeInMonths: toInteger(6), toAgeInMonths:toInteger(6), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'DTPa', fromAgeInMonths: toInteger(15), toAgeInMonths:toInteger(18), classification: 'Mandatory'}),
(:VaccineDose {name: 'Booster', vaccineName: 'DTPa', fromAgeInMonths: toInteger(48), toAgeInMonths:toInteger(60), classification: 'Mandatory'})
;
