//CREATE INITAL PATIENT'S VACCINE CARD (ALL DOSES ARE OVERDUE)
MATCH (card:VaccineCard), (dose:VaccineDose)
WHERE card.id = 'XXXX12345'
MERGE (card)-[:IS_OVERDUE]->(dose)

//CREATE INITAL PATIENT'S VACCINE CARD (ALL DOSES ARE OVERDUE)
MATCH (card:VaccineCard), (dose:VaccineDose)
WHERE card.id = 'TTTT67890'
MERGE (card)-[:IS_OVERDUE]->(dose)
